services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.15
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_REDIRECT_DISABLED=true
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
      - '29814:29814'
      - '29815:29815'
      - '29816:29816'
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    labels:
      # Define ALL Traefik labels exactly as you want them
      # This should be the *only* set of Traefik labels present
      - traefik.docker.network=dokploy-network
      - traefik.enable=true # Keep this enabled

      # HTTP Router: Redirect to HTTPS
      - traefik.http.routers.omada-web-http.rule=Host(`omada.makerusa.net`)
      - traefik.http.routers.omada-web-http.entrypoints=web
      - traefik.http.routers.omada-web-http.middlewares=redirect-to-https@file # Use Dokploy's file middleware

      # HTTPS Router: Proxy to Omada's internal 8043 (HTTPS)
      - traefik.http.routers.omada-web-https.rule=Host(`omada.makerusa.net`)
      - traefik.http.routers.omada-web-https.entrypoints=websecure
      - traefik.http.routers.omada-web-https.tls=true
      - traefik.http.routers.omada-web-https.tls.certresolver=letsencrypt # Your resolver

      # Service Definition: Points to Omada's internal 8043 (HTTPS) with insecure skip verify
      - traefik.http.services.omada-internal-https.loadbalancer.server.port=8043
      - traefik.http.services.omada-internal-https.loadbalancer.servers.transport=insecure-omada-transport@docker # Requires the transport to be defined in Traefik's dynamic config

      # Link routers to the new service
      - traefik.http.routers.omada-web-http.service=omada-internal-https
      - traefik.http.routers.omada-web-https.service=omada-internal-https
    networks:
      - dokploy-network
volumes:
  omada-data: null
  omada-logs: null
networks:
  dokploy-network:
    external: true
