version: '3.8'

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.15
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043       # ← reverted
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843       # ← reverted
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
      - "29814:29814"
      - "29815:29815"
      - "29816:29816"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network

      # HTTP (for redirect)
      - traefik.http.routers.makerusa-omada-iqpgms-6-web.rule=Host(`omada.makerusa.net`)
      - traefik.http.routers.makerusa-omada-iqpgms-6-web.entrypoints=web
      - traefik.http.routers.makerusa-omada-iqpgms-6-web.middlewares=redirect-to-https@file
      - traefik.http.routers.makerusa-omada-iqpgms-6-web.service=makerusa-omada-iqpgms-6-web
      - traefik.http.services.makerusa-omada-iqpgms-6-web.loadbalancer.server.port=8088

      # HTTPS
      - traefik.http.routers.makerusa-omada-iqpgms-6-websecure.rule=Host(`omada.makerusa.net`)
      - traefik.http.routers.makerusa-omada-iqpgms-6-websecure.entrypoints=websecure
      - traefik.http.routers.makerusa-omada-iqpgms-6-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.makerusa-omada-iqpgms-6-websecure.service=makerusa-omada-iqpgms-6-websecure
      - traefik.http.services.makerusa-omada-iqpgms-6-websecure.loadbalancer.server.port=8088

volumes:
  omada-data: null
  omada-logs: null

networks:
  dokploy-network:
    external: true
