services:
  omada-controller:
    container_name: omada-controller # Coolify might override this, but good to include
    image: mbentley/omada-controller:5.15
    restart: unless-stopped # Coolify often manages restart policies
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      # These are the internal Omada config variables
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_REDIRECT_DISABLED=true # Keep this, Omada's internal redirect handling
      - SSL_CERT_NAME=tls.crt       # Omada's internal self-signed cert
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
      # Device adoption/discovery ports (Omada needs to know these)
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
    ports:
      # These are ports that the Omada controller CONTAINER EXPOSES.
      # Coolify uses this to know what ports are available on the container.
      # You do NOT need to map them to host ports (e.g., "8088:8088") here,
      # as Coolify's internal network and Traefik will handle that.
      #
      # Just list the container's exposed ports that are relevant.
      # Coolify will ask you in the UI which of these you want exposed via Traefik (for web UI)
      # and which you want mapped directly to the host (for device adoption).
      
      # Web UI related ports (Coolify will select one for Traefik)
      - "8088" # Omada's internal HTTP management port
      - "8043" # Omada's internal HTTPS management port

      # Device adoption / discovery ports (Coolify will help map these to host)
      - "8843" # Guest portal HTTPS
      - "27001/udp"
      - "29810/udp"
      - "29811"
      - "29812"
      - "29813"
      - "29814"
      - "29815"
      - "29816"
      
    volumes:
      # Define internal container paths that need persistent storage.
      # Coolify will manage the actual host paths for these volumes.
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

# Coolify will manage networks and top-level volumes, so you usually don't
# define them here unless you have very specific multi-service networking needs
# that Coolify doesn't abstract.
# volumes:
#   omada-data:
#   omada-logs:
# networks:
#   default:
